# this is an example of the Cool Tasks Service API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Cool Tasks Service API
  version: 1.0.0
schemes:
  - http
host: localhost:8080
produces:
  - application/json
consumes:
  - application/json
paths:
  /v1/hello-world:
    get:
      summary: Hello World
      tags:
        - welcome page
      responses:
        '200':
          description: Hello World
          schema:
            $ref: '#/definitions/HelloWorldResponse'
definitions:
  HelloWorldResponse:
    type: object
    properties:
      message:
        type: string
        description: Hello World
